baseURL: "https://satalinnansaatio.fi/"
languageCode: "fi-fi"
title: "Satalinnan Säätiö"
sectionPagesMenu: "main"
publishdir: ./docs

menu:
  main:
    - identifier: satakuntatalo
      name: Satakuntatalo
      url: /satakuntatalo/
      weight: 1

    - identifier: lahjoittaminen
      name: Lahjoittaminen
      url: /lahjoittaminen/
      weight: 2

    - identifier: yhteystiedot
      name: Yhteystiedot
      url: /yhteystiedot/
      weight: 3
